"""
Orbit — FastAPI server entry point.

Exposes the multi-agent Orbit system as a REST + SSE API using ADK's get_fast_api_app.

Endpoints (auto-generated by ADK):
  GET  /health                                              — liveness check
  GET  /list-apps                                           — list agent apps
  POST /apps/{app}/users/{uid}/sessions/{sid}              — create/reset session
  GET  /apps/{app}/users/{uid}/sessions/{sid}              — get session state
  POST /run                                                 — run agent (blocking)
  POST /run_sse                                             — run agent with SSE streaming

Run:
  python main.py
  uvicorn main:app --host 0.0.0.0 --port 8080 --reload
"""

import os
from pathlib import Path

import uvicorn
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from google.adk.cli.fast_api import get_fast_api_app

from orbit.config import PORT, SESSIONS_DB, APP_NAME

# Directory containing the `orbit/` package (i.e. backend/)
AGENTS_DIR = str(Path(__file__).parent)

# Build the ADK-powered FastAPI app
# session_service_uri: SQLite for persistence across restarts (use None for in-memory)
app: FastAPI = get_fast_api_app(
    agents_dir=AGENTS_DIR,
    session_service_uri=f"sqlite+aiosqlite:///{SESSIONS_DB}",
    allow_origins=["*"],   # tighten this in production
    web=False,             # set True to also serve the ADK dev UI
)

# Add CORS middleware (ADK's get_fast_api_app sets allow_origins but this makes it explicit)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── custom endpoints ──────────────────────────────────────────────────────────

@app.get("/health", tags=["Meta"])
async def health() -> dict:
    """Liveness check — returns app name and status."""
    return {"status": "ok", "app": APP_NAME}


# ── entry point ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    uvicorn.run(
        "main:app",
        host="0.0.0.0",
        port=PORT,
        reload=True,
        log_level="info",
    )
